server:  port: 8751
spring:
  application:    name: api-Gateway
  cloud:
    gateway:
      discovery:        locator:          enabled: true
          lower-case-service-id: true
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods:
            - GET            - POST            - PUT            - DELETE